name: Prevent Supabase Inactivity

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Make an API request to Supabase
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Update Database
        run: npx tsx src/utils/workflow.ts
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
